import React, {Component} from 'react'
import { Text, View, TouchableOpacity } from 'react-native'
import { Marker, Callout } from 'react-native-maps'
import { SearchBar, Overlay  } from 'react-native-elements'
import Axios from 'axios';
import POISCallout from './POISCallout'

export default class POIS extends Component{

    constructor(props) {
        super(props);
    
        this.state = {
            POIS: [],
            render: [],
            show: false
        }
        this.returnInfo = this.returnInfo.bind(this)
    }
    
    returnInfo(){
      console.log("Hi")
    }

    componentDidMount(){
        Axios.get("https://inmyseat.chronicle.horizon.ac.uk/api/v1/allpois")
        .then(response =>{
          return response.data
        })
        .then(data => this.setState({ POIS: data}))
        .then( () => {
          var render = []
          for(let i = 0; i < this.state.POIS.length; i++){
            render[i] = false
          }
          return render
        })
        .then(data => this.setState({render: data}))
    }

    render(){
        return(
          <>
            {
              this.state.POIS.map((item, i) =>{
                if(item.category === this.props.filter || this.props.filter === "N/A"){
                  return(
                    <Marker
                    key={i}
                    onPress={
                      () =>{
                        this.props.showOverlay()
                        this.props.showItem(item)
                      }
                    }
                    name={item.name}
                    coordinate={{latitude: item.latitude, longitude: item.longitude}}
                    image={require('../../assets/icons8-point-of-interest-52.png')}
                    >
                    </Marker>
                  )
                }
              })
            }
            
          </>
          )
          
    }
}

/*

var temp = this.state.render
                        temp[i] = true
                        this.setState({
                          render: temp
                        })
                        //this.setState({show: true})

<Callout onPress={()=>{ console.log("I am: " + i), this.returnInfo() }}>
                      <POISCallout item={item} render={this.state.render[i]} />
                  </Callout>

this.refs.modal7.open()
<Modal ref={"modal7"} position={"center"}>
                  <View>
                    <TextInput style={{height: 50, width: 200, backgroundColor: '#DDDDDD'}}/>
                  </View>
                </Modal>
NotificationsAndroid.setNotificationReceivedListener((notification) => {
        console.log("Notification received on device in background or foreground", notification.getData());
      });
      NotificationsAndroid.setNotificationReceivedInForegroundListener((notification) => {
        console.log("Notification received on device in foreground", notification.getData());
      });
      NotificationsAndroid.setNotificationOpenedListener((notification) => {
        console.log("Notification opened by device user", notification.getData());
      });
NotificationsAndroid.localNotification({
        title: "Local notification",
        body: "This notification was generated by the app!",
        extra: "data"
      })
*/